
OS: OSX
osx_image: xcode14.2
language: swift
PATH: /3. EssentialFeedProject/EssentialFeedProject/EssentialFeed
script: xcodebuild clean build test -project "${PATH}/EssentialFeed.xcodeproj" -scheme "CI" CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO
