
OS: OSX
osx_image: xcode14.3
language: swift
# whitelist
branches:
  only:
    - master
script: 
- xcodebuild clean build test -project 3.EssentialFeedProject/EssentialFeedProject/EssentialFeed/EssentialFeed.xcodeproj -scheme "CI_macOS" CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO -sdk macosx -destination "platform=macOS,OS=13.1" ONLY_ACTIVE_ARCH=YES
- xcodebuild clean build test -workspace 4.EssentialApp/EssentialApp/EssentialApp.xcworkspace -scheme "CI_iOS" CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO -sdk iphonesimulator -destination "platform=iOS Simulator,OS=16.4,name=iPhone 14 Pro" ONLY_ACTIVE_ARCH=YES
